version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: 'redis:7-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  backend:
    stdin_open: true
    container_name: companyx_api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
      - "1234:1234"
    depends_on:
      - db
      - redis

  frontend:
    stdin_open: true
    container_name: companyx_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "npm run dev"
    volumes:
    - ./frontend:/app
    ports:
      - "5001:5001"
    depends_on:
      - backend

volumes:
  postgres:
  redis: